include:
  - docker-compose.db.yaml

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backstage_backend
    restart: no
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://admin:adminpass@postgres:5432/num_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "watchmedo auto-restart --directory=/backend/core --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000"
